# Generated by Django 3.0.8 on 2020-07-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('desc', models.TextField(verbose_name='簡單描述')),
            ],
            options={
                'verbose_name': '关于',
                'verbose_name_plural': '关于',
                'db_table': 'about',
            },
        ),
        migrations.CreateModel(
            name='BookLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('link', models.CharField(max_length=200, verbose_name='链接')),
            ],
            options={
                'verbose_name': '书籍链接',
                'verbose_name_plural': '书籍链接',
                'db_table': 'booklink',
            },
        ),
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('link', models.CharField(max_length=200, verbose_name='链接')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
                'db_table': 'friendlink',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('desc', models.TextField(verbose_name='簡單描述')),
            ],
            options={
                'verbose_name': '首页信息',
                'verbose_name_plural': '首页信息',
                'db_table': 'home',
            },
        ),
        migrations.CreateModel(
            name='MySiteData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts', models.IntegerField(default=0, verbose_name='文章数')),
                ('categories', models.IntegerField(default=0, verbose_name='分类数')),
                ('tags', models.IntegerField(default=0, verbose_name='标签数')),
                ('readers', models.IntegerField(default=0, verbose_name='读者数')),
                ('pageviews', models.IntegerField(default=0, verbose_name='浏览数')),
            ],
            options={
                'verbose_name': '网站数据',
                'verbose_name_plural': '网站数据',
                'db_table': 'mysitedata',
            },
        ),
    ]
